// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNNrUdRrR4nhQBlGwGclo9IakNV8hxyp4',
    appId: '1:821867387225:android:0b1bb35e9bd4a5123a1448',
    messagingSenderId: '821867387225',
    projectId: 'ms-chat-d21d3',
    storageBucket: 'ms-chat-d21d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-GlH7MJUT4FsaGIGtA3bX0yT0hkWeILQ',
    appId: '1:821867387225:ios:afcbbd5298b8353d3a1448',
    messagingSenderId: '821867387225',
    projectId: 'ms-chat-d21d3',
    storageBucket: 'ms-chat-d21d3.appspot.com',
    androidClientId: '821867387225-lm6v5obbsqkrirvlfkdvo9ak9kocqq9t.apps.googleusercontent.com',
    iosClientId: '821867387225-em983ac3kmeaqboooengfbharpchgm3r.apps.googleusercontent.com',
    iosBundleId: 'com.mukeshsheoran.msChat',
  );
}
